services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    entrypoint: >
      sh -c "
        # Create a temporary user
        adduser --disabled-password --gecos '' deployuser
        # Ensure wp-config.php is owned by www-data (33:33 by default)
        chown 33:33 /var/www/html/wp-config.php && \
        # Run wp-cli as deployuser only if WordPress isn't installed
        su deployuser -c '
          wp core is-installed || wp core install --url=${WORDPRESS_URL} --title=\"${WORDPRESS_SITE_TITLE}\"  --admin_user=\"${WORDPRESS_ADMIN_USER}\" --admin_password=\"${WORDPRESS_ADMIN_PASSWORD}\" --admin_email=\"${WORDPRESS_ADMIN_EMAIL}\"
        ' && \
        # Start Apache as normal
        exec apache2-foreground
      "
    volumes:
     - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp-net

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups
    networks:
      - wp-net

volumes:
  db_data:

networks:
  wp-net:
