name: Restore latest saved wordpress state from artifacts (Manual trigger)
on:
  workflow_dispatch:
jobs:
  restore-wordpress-state:
    runs-on: self-hosted
    steps: 
      - name: Install GitHub CLI and jq
        run: |
          echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update
          echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y gh jq
      - name: Create restore directory - temporary for testing
        run: |
          echo "Creating restore directory"
          mkdir -p ./wp-restored
      - name: Find last successful run of saving state workflow
        id: get_run
        run: |
          run_id=$(gh run list --workflow app_save_current_state.yml --status success --limit 1 --json databaseId | jq -r '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact from last successful run
        run: |
          gh run download ${{ steps.get_run.outputs.run_id }} -n wordpress-backup -D ./wp-restored/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check if wp-restored and wp-backup directories contains same files
        run: |
          echo "Checking if wp-restored and wp-backup directories contain the same files"
          if diff -qr ./wp-restored ./wp-backup; then
            echo "Directories are identical"
            echo "No need to restore, exiting"
            exit 1
          else
            echo "::warning:: Directories differ, proceeding with restore"
          fi
          