name: App Test

on:
  workflow_call:

jobs:
    check-if-containers-are-running:
      runs-on: self-hosted
      steps:
        - name: Check if containers are running
          run: |
            required_containers=(db wordpress https)
            missing=0
            for c in "${required_containers[@]}"; do
              if ! docker ps --format '{{.Names}}' | grep -qw "$c"; then
                echo "Container $c is NOT running."
                missing=1
              else
                echo "Container $c is running."
              fi
            done
            if [ "$missing" -eq 1 ]; then
              echo "One or more required containers are not running."
              exit 1
            fi
    check-if-database-is-ready:
      runs-on: self-hosted
      steps:
        - name: Check if database is ready
          run: |
            if docker exec db mysqladmin ping --silent; do
              echo "Database is ready."
            else
              echo "Database is not ready"
              exit 1
            fi
    check-if-wordpress-is-ready:
        runs-on: self-hosted  
        steps:
          - name: Check if website is ready
            uses: jtalk/url-health-check-action@v4
            with:
                #https://github.com/marketplace/actions/url-health-check
                url: https://localhost|https://localhost/wp-admin|https://localhost/wp-login.php
                max-attempts: 3
                retry-delay: 5s