name: Validate Docker Compose File

on:
  workflow_call:
    secrets:
      WORDPRESS_ADMIN_PASSWORD: 
        required: true
      WORDPRESS_DB_PASSWORD: 
        required: true
      MYSQL_ROOT_PASSWORD: 
        required: true

jobs:
  docker-comnpse-dry-dun:
    runs-on: self-hosted
    steps:
      - name: Check if anything had to be installed
        if: ${{ needs.check-out-environment.outputs.docker_installed == '2' || needs.check-out-environment.outputs.docker_compose_installed == '2' || needs.check-out-environment.outputs.mkcert_installed == '2' }}
        run: |
          if [ "${{ needs.check-out-environment.outputs.docker_installed }}" == "2" ]; then
            echo "::warning:: docker had to be installed by cicd workflow. Please check runner status"
            exit 1
          fi
          if [ "${{ needs.check-out-environment.outputs.docker_compose_installed }}" == "2" ]; then
            echo "::warning:: docker compose had to be installed by cicd workflow. Please check runner status"
            exit 1
          fi
          if [ "${{ needs.check-out-environment.outputs.mkcert_installed }}" == "2" ]; then
            echo "::warning:: mkcert had to be installed by cicd workflow. Please check runner status"
            exit 1
          fi
      - name: Dry-run app
        run: docker compose -f webapp/docker-compose.yml up -d --dry-run
        env:
          WORDPRESS_SITE_TITLE: ${{ vars.WORDPRESS_SITE_TITLE }}
          WORDPRESS_ADMIN_USER: ${{ vars.WORDPRESS_ADMIN_USER }}
          WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
          WORDPRESS_ADMIN_EMAIL: ${{ vars.WORDPRESS_ADMIN_EMAIL }}
          WORDPRESS_DB_NAME: ${{ vars.WORDPRESS_DB_NAME }}
          WORDPRESS_DB_USER: ${{ vars.WORDPRESS_DB_USER }}
          WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
