name: WordPress Configuration
on:
  workflow_dispatch:
  workflow_call:

jobs:
  add-user:
    runs-on: [self-hosted]
    steps:
      - name: Install WP-CLI
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/installwpcli.sh"
      - name: Check if database is ready
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/checkdb.sh"
      - name: Configure WordPress
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/installwp.sh"
      - name: Set up urls
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/setupurls.sh"