name: Restore latest saved wordpress state from artifacts (Manual trigger)
on:
  workflow_dispatch:
    inputs:
      check_if_identical:
        description: 'Check if restored state is identical to backup'
        required: false
        default: false
        type: boolean
jobs:
  download-wordpress-state:
    runs-on: self-hosted
    steps: 
      - name: Install GitHub CLI and jq
        run: |
          echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update
          echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y gh jq
      - name: Create restore directory - temporary for testing
        run: |
          echo "Creating restore directory"
          mkdir -p ./wp-restored
      - name: Find last successful run of saving state workflow
        id: get_run
        run: |
          run_id=$(gh run list --workflow app_save_current_state.yml --status success --limit 1 --json databaseId | jq -r '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact from last successful run
        run: |
          gh run download ${{ steps.get_run.outputs.run_id }} -n wordpress-backup -D ./wp-restored/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  restore-wordpress-state-from-backup:
    runs-on: self-hosted
    needs: download-wordpress-state
    steps:
      - name: Restore WordPress state from backup
        run: |
          echo "Restoring WordPress state from backup"
          docker cp ./wp-restored/. wordpress:/var/www/html/
          echo "WordPress state restored successfully from backup"
      - name: Restore database from backup
        run: |
          echo "Restoring database from backup"
          docker exec wordpress wp db import ./wp-restored/wordpress-db.sql --allow-root --path=/var/www/html
          echo "Database restored successfully from backup"