name: Validate Docker Compose File

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate-app:
    runs-on: [self-hosted]
    steps:
      - run: docker compose --env-file .env -f webapp/docker-compose.yml up -d --dry-run
