name: App Configuration
on:
  workflow_call:

jobs:
  configure-nginx:
    runs-on: self-hosted
    steps:
      - name: Create https certificates if not exist
        run: | 
          if [ ! -f ./localhost.pem ] || [ ! -f ./localhost-key.pem ]; then
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S  mkcert -install
            echo "Creating certificates..."
            mkcert localhost
          else
            echo "Certificates already exist."
          fi
      - name: Move Nginx configuration files
        run: |
          docker cp localhost.pem https:/etc/nginx/conf.d/localhost.pem
          docker cp localhost-key.pem https:/etc/nginx/conf.d/localhost-key.pem
          docker cp ./webapp/nginx-config/default.conf https:/etc/nginx/conf.d/default.conf
          docker exec https /bin/bash -c "service nginx reload"
  install-wp-cli:
    runs-on: self-hosted
    steps:
      - name: Install WP-CLI
        run: |
          docker exec wordpress /bin/bash -c "
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar;
            chmod +x wp-cli.phar;
            mv wp-cli.phar /usr/local/bin/wp
          "
      - name: Check if database is ready
        run: |
          docker exec wordpress /bin/bash -c " 
            until echo > /dev/tcp/db/3306; do
              echo 'Waiting for database connection...';
              sleep 3;
            done;
            echo 'Database is ready'
          "
  find-wp-backup:
    uses: ./.github/workflows/app_find_wp_backup.yml
  configure-wp-from-backup:
    if: ${{ needs.find-wp-backup.outputs.run_id != '' }}
    needs: find-wp-backup
    uses: ./.github/workflows/app_restore_wp_backup.yml
    with:
          run_id: ${{ needs.find-wp-backup.outputs.run_id }}
  configure-plain-wordpress:
    if: ${{ needs.find-wp-backup.outputs.run_id == '' }} || ${{ needs.configure-wp-from-backup.result == 'failure' }}
    runs-on: self-hosted
    needs: [install-wp-cli, find-wp-backup, configure-wp-from-backup]
    steps:
      - name: Configure WordPress
        run: |
          docker exec wordpress /bin/bash -c "
            wp core install \
            --url="localhost" \
            --title="${{ vars.WORDPRESS_SITE_TITLE }}" \
            --admin_user="${{ vars.WORDPRESS_ADMIN_USER }}" \
            --admin_password="${{ secrets.WORDPRESS_ADMIN_PASSWORD }}" \
            --admin_email="${{ vars.WORDPRESS_ADMIN_EMAIL }}" \
            --allow-root --path=/var/www/html
          "