name: Restore latest saved wordpress state from artifacts (Manual trigger)
on:
  workflow_dispatch:

jobs:
  download-wordpress-backup:
    runs-on: self-hosted
    steps: 
      - name: Create restore directory - temporary for testing
        run: |
          echo "Creating restore directory"
          mkdir -p ./wp-restored
      - name: Find last successful run of saving state workflow
        id: get_run
        run: |
          run_id=$(gh run list --workflow app_save_current_state.yml --status success --limit 1 --json databaseId | jq -r '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact from last successful run
        run: |
          gh run download ${{ steps.get_run.outputs.run_id }} -n wordpress-backup -D ./wp-restored/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  restore-wordpress-state-from-backup:
    runs-on: self-hosted
    needs: download-wordpress-backup
    steps:
      - name: Restore WordPress state from backup
        run: |
          echo "Restoring WordPress state from backup"
          docker cp ./wp-restored/. wordpress:/var/www/html/
          echo "WordPress state restored successfully from backup"
      - name: Restore database from backup
        run: |
          echo "Restoring database from backup"
          docker exec wordpress wp db import ./wp-restored/wordpress-db.sql --allow-root --path=/var/www/html
          echo "Database restored successfully from backup"
  remove-backup-directory:
    runs-on: self-hosted
    needs: restore-wordpress-state-from-backup
    steps:
      - name: Remove temporary backup directory
        run: |
          echo "Removing temporary backup directory"
          rm -rf ./wp-restored
          echo "Temporary backup directory removed successfully"