name: simple pipeline
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  pre-checks:
    runs-on: self-hosted
    steps:
      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed!"
            exit 1
          else
            echo "Docker is installed."
          fi
  test-branch:
    needs: pre-checks
    if: github.ref != 'refs/heads/main'
    runs-on: [self-hosted, test]
    steps:
      - name: Run a one-line script
        run: echo "test branch"
  main-branch:
    needs: pre-checks
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, main]
    steps:
      - name: Run a one-line script
        run: echo "main branch"
