name: simple pipeline
on:
  push:
    branches: [ "wordpress", "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pre-checks:
    runs-on: self-hosted
    steps:
      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed!"
            exit 1
          else
            echo "Docker is installed."
          fi
  clean-last-build:
    needs: pre-checks
    runs-on: [self-hosted, test]
    steps:
      - name: Cleanup Existing Container
        run: |
          echo "Cleaning up existing Docker container if it exists"
          if [ "$(docker ps -a -q -f name=wordpress)" ]; then
            docker stop wordpress || true
            docker rm wordpress || true
          fi
          echo "Cleaning up existing Docker image if it exists"
          if [ "$(docker images -q wordpress)" ]; then
            docker rmi wordpress || true
          fi
  checkout-new-code:
    needs: [pre-checks, clean-last-build]
    runs-on: [self-hosted, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
  create-env-file:
    needs: pre-checks
    runs-on: [self-hosted, test]
    steps:
      - name: Create .env file
        run: |
          echo "WORDPRESS_DB_NAME=${{ vars.WORDPRESS_DB_NAME }}" >> .env
          echo "WORDPRESS_DB_USER=wpu${{ vars.WORDPRESS_DB_USER }}ser" >> .env
          echo "WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
  validate-app:
    needs: [pre-checks, clean-last-build, create-env-file]
    runs-on: [self-hosted, test]
    steps:
      - name: Validate Docker Compose File
        run: docker compose --env-file .env -f webapp/docker-compose.yml config
  run-app:
    needs: [pre-checks, clean-last-build, validate-app, create-env-file]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, main]
    steps:
      - name: Start WordPress Stack
        run: docker compose --env-file .env -f webapp/docker-compose.yml up -d
