name: main pipeline
on:
  push:
  #  branches: [ "database", "main" ]
    paths-ignore:
      - 'README.md'
  # pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  pre-checks:
    runs-on: [self-hosted]
    steps:
      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed!"
            exit 1
          else
            echo "Docker is installed."
          fi
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Clean up last build
        run: |
          docker compose -f webapp/docker-compose.yml down -v --rmi all --remove-orphans
          docker system prune -af --volumes
  create-env-file:
    needs: pre-checks
    runs-on: [self-hosted]
    steps:
      - name: Create .env file
        run: |
          echo "WORDPRESS_SITE_TITLE=${{ vars.WORDPRESS_SITE_TITLE }}" >> .env
          echo "WORDPRESS_ADMIN_USER=${{ vars.WORDPRESS_ADMIN_USER }}" >> .env
          echo "WORDPRESS_ADMIN_PASSWORD=${{ secrets.WORDPRESS_ADMIN_PASSWORD }}" >> .env
          echo "WORDPRESS_ADMIN_EMAIL=${{ vars.WORDPRESS_ADMIN_EMAIL }}" >> .env      
          echo "WORDPRESS_DB_NAME=${{ vars.WORDPRESS_DB_NAME }}" >> .env
          echo "WORDPRESS_DB_USER=${{ vars.WORDPRESS_DB_USER }}" >> .env
          echo "WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
  mount-volumes:
    needs: pre-checks
    runs-on: [self-hosted]
    steps:
      - name: Prepare bind mount directories
        run: |
          export DIRS="webapp/backups"
          mkdir -p $DIRS
          chown ${{ vars.OS_USERNAME }}:${{ vars.OS_USERGROUP }} $DIRS
  validate-app:
    needs: 
      - mount-volumes
      - create-env-file
    runs-on: [self-hosted]
    steps:
      - name: Validate Docker Compose File
        run: docker compose --env-file .env -f webapp/docker-compose.yml up -d --dry-run
  run-app-dev:
    needs: validate-app
    runs-on: [self-hosted]
    steps:
      - name: Start WordPress dev Stack
        run: docker compose --env-file .env -f webapp/docker-compose.yml up -d --build
  run-app-prod:
    needs: validate-app
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, main]
    steps:
      - name: Start WordPress prod Stack
        run: docker compose --env-file .env -f webapp/docker-compose.yml up -d
  modify-container-config:
    #dev or prod need to be successful (https://stackoverflow.com/a/66358138)
    needs: [run-app-dev, run-app-prod]
    if: |
      always() && contains(needs.*.result, 'success') && !contains(needs.*.result, 'failure')
    runs-on: [self-hosted]
    steps:
      - name: Modify WordPress container configuration
        run: |
          docker exec wordpress /bin/bash -c "chown -R www-data:www-data /var/www/wordpress-config/" 
          docker exec wordpress /bin/bash -c "adduser --disabled-password --gecos '' deployuser"
          docker exec wordpress /bin/bash -c "mv /var/www/wordpress-config/wp-config.php /var/www/html/wp-config.php"
          docker exec wordpress /bin/bash -c "chmod +x /var/www/wordpress-config/configcli.sh"
          docker exec wordpress /bin/bash -c "./var/www/wordpress-config/configcli.sh"

