name: simple pipeline
on:
  push:
    branches: ${{ vars.PUSH_BRANCHES }}
  pull_request:
    branches: ${{ vars.PR_BRANCHES }}
  workflow_dispatch:
jobs:
  test-branch:
    if: github.ref != 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world from test branch!"
  main-branch:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world from main branch!"
