name: simple pipeline
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  pre-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed!"
            exit 1
          else
            echo "Docker is installed."
          fi
  build-app:
    needs: pre-checks
    runs-on: [self-hosted, test]
    steps:
      - name: Cleanup Existing Container
        run: |
          if [ "$(docker ps -a -q -f name=flask-app)" ]; then
            docker stop flask-app || true
            docker rm flask-app || true
          fi
      - name: Build Docker Image
        run: docker build -t flask-app ./webapp
      - name: Inspect Docker Image
        run: docker inspect flask-app
  run-app:
    needs: pre-checks
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, main]
    steps:
      - name: Run Flask Container
        run: docker run -d -p 5000:5000 --name flask-app flask-app
