name: main pipeline
on:
  push:
  # branches: [ "database", "main" ]
    paths-ignore:
      - 'README.md'
  # pull_request:
  # branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  set-up-environment:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Check and Install Docker & Compose
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
          else
            echo "Docker is already installed."
          fi
          if ! docker compose version &> /dev/null; then
            echo "Docker Compose is not installed. Installing Compose..."
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          else
            echo "Docker Compose is already installed."
          fi
      - name: Clean up last build
        run: |
          docker compose -f webapp/docker-compose.yml down -v --rmi all --remove-orphans
          docker system prune -af --volumes
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_WORDPRESS_SITE_TITLE: ${{ vars.WORDPRESS_SITE_TITLE }}
          envkey_WORDPRESS_ADMIN_USER: ${{ vars.WORDPRESS_ADMIN_USER }}
          envkey_WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
          envkey_WORDPRESS_ADMIN_EMAIL: ${{ vars.WORDPRESS_ADMIN_EMAIL }}    
          envkey_WORDPRESS_DB_NAME: ${{ vars.WORDPRESS_DB_NAME }}
          envkey_WORDPRESS_DB_USER: ${{ vars.WORDPRESS_DB_USER }}
          envkey_WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
          envkey_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Prepare bind mount directories
        run: |
          export DIRS="webapp/backups"
          mkdir -p $DIRS
          chown ${{ vars.OS_USERNAME }}:${{ vars.OS_USERGROUP }} $DIRS
      - name: create certificates if not exist
        run: | 
          if [ ! -f ./localhost.pem ] || [ ! -f ./localhost-key.pem ]; then
            echo "Creating certificates..."
            if ! command -v mkcert &> /dev/null; then
              echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update -y
              echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y libnss3-tools mkcert
              mkcert -install
            fi
            mkcert localhost
            mv *.pem ./webapp/nginx-config/
          else
            echo "Certificates already exist."
          fi

  validate-app:
    needs: set-up-environment
    runs-on: [self-hosted]
    steps:
      - name: Validate Docker Compose File
        run: docker compose --env-file .env -f webapp/docker-compose.yml up -d --dry-run

  run-app:
    needs: validate-app
    runs-on: [self-hosted]
    steps:
      - name: Start WordPress Containers
        run: |
          echo "for detailed wiev run command 'docker compose --env-file .env -f webapp/docker-compose.yml up -d --build'" 
          docker compose --env-file .env -f webapp/docker-compose.yml up -d --build
      - name: Copy Nginx configuration files to container
        run: |
          docker exec https /bin/bash -c "mv /etc/nginx/nginx-config/* /etc/nginx/conf.d/ && service nginx reload"
      - name: Copy wordpress configuration files to container
        run: |
          docker exec wordpress /bin/bash -c "chmod +x /var/www/wordpress-config/*.sh"
      - name: Add user for wordpress CLI
        run: |
          docker exec wordpress /bin/bash -c "adduser --disabled-password --gecos '' deployuser"
      - name: Install WP-CLI
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/installwpcli.sh"
      - name: Configure WordPress
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/configurewp.sh"
      - name: allow http
        run: |
          docker exec wordpress /bin/bash -c "/var/www/wordpress-config/allowhttp.sh"

  notify-on-fail:
    needs: [run-app]
    runs-on: [self-hosted]
    steps:
      - name: Notify Discord on failure
        #https://github.com/marketplace/actions/actions-status-discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "❌ Build Failed"
          description: "Job `${{ github.job }}` in workflow `${{ github.workflow }}` failed on `${{ github.ref_name }}`."
          color: 0xff0000
