name: Main Pipeline

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  clean-up-last-build:
    uses: ./.github/workflows/environment_docker_cleanup.yml
    
  prepare-environment:
    needs: clean-up-last-build
    uses: ./.github/workflows/environment_prepare.yml
    secrets: 
      inherit

  run-app:
    needs: prepare-environment
    uses:  ./.github/workflows/app_run.yml
    secrets:
      inherit

  validate-app:
    needs: run-app
    uses: ./.github/workflows/app_validate.yml
    secrets:
      inherit
  
  #TODO create artifact with app #58
 
  #stop-app:
  #  if: github.ref_name != 'main'
  #  needs: run-app
  #  uses: ./.github/workflows/environment_docker_cleanup.yml

  notify-if-any-step-fails:
    needs: [prepare-environment, validate-app, run-app]
    if: failure() || cancelled()
    uses: ./.github/workflows/notification_discord.yml
    secrets:
      inherit
