name: Main Pipeline

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  clean-up-last-build:
    uses: ./.github/workflows/environment_docker_cleanup.yml
    
  prepare-environment:
    needs: clean-up-last-build
    uses: ./.github/workflows/environment_prepare.yml
    secrets: 
      inherit

  validate-app:
    needs: prepare-environment
    uses: ./.github/workflows/app_validate.yml
    with:
      docker_installed_by_cicd: ${{ needs.prepare-environment.outputs.docker_installed_by_cicd }}
      docker_compose_installed_by_cicd: ${{ needs.prepare-environment.outputs.docker_compose_installed_by_cicd }}
      mkcert_installed_by_cicd: ${{ needs.prepare-environment.outputs.mkcert_installed_by_cicd }}
    secrets:
      inherit

  run-app:
    needs: validate-app
    uses:  ./.github/workflows/app_run.yml
    secrets:
      inherit

  notify-if-any-step-fails:
    needs: [prepare-environment, validate-app, run-app]
    if: failure() || cancelled()
    uses: ./.github/workflows/notification_discord.yml
    secrets:
      inherit
