name: Main Pipeline

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  clean-up-last-build:
    uses: ./.github/workflows/environment_docker_cleanup.yml
    
  prepare-environment:
    needs: clean-up-last-build
    uses: ./.github/workflows/environment_prepare.yml
    secrets: 
      WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      RUNNER_SUDO_PASSWD: ${{ secrets.RUNNER_SUDO_PASSWD }}

  validate-app:
    needs: prepare-environment
    uses: ./.github/workflows/app_validate.yml
    secrets:
      WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

  run-app:
    needs: validate-app
    uses:  ./.github/workflows/app_run.yml
    secrets:
      WORDPRESS_ADMIN_PASSWORD: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

  notify-if-any-step-fails:
    needs: [prepare-environment, validate-app, run-app]
    if: failure() || cancelled()
    uses: ./.github/workflows/notification_discord.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
