name: Cleanup Docker Images and Containers

on:
  workflow_call: 

jobs:
  cleanup-docker:
    runs-on: self-hosted
    steps:
        - run: |
            docker compose -f webapp/docker-compose.yml down -v --rmi all --remove-orphans
            docker system prune -af --volumes
