name: Prepare Environment

on:
  workflow_call: 
    secrets:
      WORDPRESS_ADMIN_PASSWORD: 
        required: true
      WORDPRESS_DB_PASSWORD: 
        required: true
      MYSQL_ROOT_PASSWORD: 
        required: true
      RUNNER_SUDO_PASSWD: 
        required: true
  
jobs:
  check-out-environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Check if components are installed
        id: check
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. It will be installed in the next step." 
            echo "docker_installed=0" >> $GITHUB_OUTPUT
          else
            echo "Docker is already installed."
            echo "docker_installed=1" >> $GITHUB_OUTPUT
          fi
          if ! docker compose version &> /dev/null; then
            echo "Docker Compose is not installed. It will be installed in the next step."
            echo "docker_compose_installed=0" >> $GITHUB_OUTPUT
          else
            echo "Docker Compose is already installed."
            echo "docker_compose_installed=1" >> $GITHUB_OUTPUT
          fi
          if ! command -v mkcert &> /dev/null; then
            echo "mkcert is not installed. It will be installed in the next step."
            echo "mkcert_installed=0" >> $GITHUB_OUTPUT
          else 
            echo "mkcert is already installed."
            echo "mkcert_installed=1" >> $GITHUB_OUTPUT     
          fi
      - name: Install components if not installed
        if: steps.check.outputs.docker_installed == '0' || steps.check.outputs.docker_compose_installed == '0' || steps.check.outputs.mkcert_installed == '0'
        run: |
          if [ "${{ steps.check.outputs.docker_installed }}" == "0" ]; then
            echo "Installing Docker..."
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update -y
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y docker.io
            sudo systemctl enable --now docker
            # curl -fsSL https://get.docker.com -o get-docker.sh
            # sudo sh get-docker.sh
            # sudo usermod -aG docker $USER
            echo "docker_installed=2" >> $GITHUB_OUTPUT
          fi
          if [ "${{ steps.check.outputs.docker_compose_installed }}" == "0" ]; then
            echo "Installing Docker Compose..."
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            echo "docker_compose_installed=2" >> $GITHUB_OUTPUT
          fi
          if [ "${{ steps.check.outputs.mkcert_installed }}" == "0" ]; then
            echo "Installing mkcert..."
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update -y
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y libnss3-tools mkcert
            echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S  mkcert -install
            echo "mkcert_installed=2" >> $GITHUB_OUTPUT
          fi
      - name: Prepare bind mount directories
        run: |
          export DIRS="webapp/backups"
          mkdir -p $DIRS
          chown ${{ vars.OS_USERNAME }}:${{ vars.OS_USERGROUP }} $DIRS
      - name: Create https certificates if not exist
        run: | 
          if [ ! -f ./localhost.pem ] || [ ! -f ./localhost-key.pem ]; then
            echo "Creating certificates..."
            mkcert localhost
            mv *.pem ./webapp/nginx-config/
          else
            echo "Certificates already exist."
          fi