name: Cleanup existing docker containers and volumes

on:
  workflow_call: 

jobs:
  cleanup-docker:
    runs-on: self-hosted
    steps:
      - name: remove docker containers and volumes
        uses: nick-fields/retry@v3
        #https://github.com/marketplace/actions/retry-step
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            echo "Cleaning up Docker containers and images..."
            docker compose -f webapp/docker-compose.yml down
            docker containers prune -f
            docker volumes prune -f
