name: Prepare Environment

on:
  workflow_call: 

jobs:
  check-components:
    runs-on: self-hosted
    outputs:
      missing: ${{ steps.check-components.outputs.missing }}
    steps:
      - name: Check if components are installed
        id: check-components
        run: |
          missing=""
          for comp in docker docker-compose mkcert gh jq; do
            if ! command -v $comp &> /dev/null; then
              missing="$missing,$comp"
            fi
          done
          # Remove leading comma
          missing="${missing#,}"
          echo "missing=$missing" >> $GITHUB_OUTPUT
          
  install-components:
    runs-on: self-hosted
    needs: check-components
    if: needs.check-components.outputs.missing != ''
    steps:
      - name: Install components if not installed
        run: |
          missing="${{ needs.check-components.outputs.missing }}"
          echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt update -y
          for comp in $(echo $missing | tr ',' ' '); do
            case $comp in
              docker)
                echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y docker.io
                sudo systemctl enable --now docker
                ;;
              mkcert)
                echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y libnss3-tools mkcert
                ;;
              *)
                echo "${{ secrets.RUNNER_SUDO_PASSWD }}" | sudo -S apt install -y $comp
                ;;
            esac
            echo "::warning:: $comp had to be installed by cicd workflow. Please check runner status"
          done