name: Main Pipeline - Deploys Wordpress Application

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:   
  prepare-environment:
    uses: ./.github/workflows/environment_prepare.yml
    secrets: 
      inherit
  checkout-code:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
  clean-up-last-build:
    needs: prepare-environment
    uses: ./.github/workflows/environment_docker_cleanup.yml
  start-app:
    needs: [clean-up-last-build, checkout-code]
    uses:  ./.github/workflows/app_run.yml
    secrets:
      inherit
  configure-app:
    needs: start-app
    uses: ./.github/workflows/app_configure.yml
    secrets:
      inherit
  validate-app:
    needs: configure-app
    uses: ./.github/workflows/app_validate.yml
    secrets:
      inherit

  notify-if-any-step-fails:
    needs: [prepare-environment, checkout-code, clean-up-last-build, validate-app, start-app, configure-app]
    if: failure() || cancelled()
    uses: ./.github/workflows/notification_discord.yml
    secrets:
      inherit