name: Main Pipeline - Deploys Wordpress Application

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/workflows/app_troubleshoot.yml'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:   
  prepare-environment:
    uses: ./.github/workflows/environment_prepare.yml
    secrets: 
      inherit

  checkout-code:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
  
  clean-up-last-build:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: remove docker containers and volumes
        run: |
          echo "Stopping and removing WordPress containers..."
          docker compose -f webapp/docker-compose.yml down
          echo "Pruning unused Docker containers..."
          docker containers prune -f
          echo "Pruning unused Docker volumes..."
          docker volumes prune -f

  start-containers:
    runs-on: self-hosted
    needs: [clean-up-last-build, checkout-code]
    steps:
      - name: Start WordPress Containers
        uses: nick-fields/retry@v3
        #https://github.com/marketplace/actions/retry-step
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            WORDPRESS_SITE_TITLE="${{ vars.WORDPRESS_SITE_TITLE }}" \
            WORDPRESS_ADMIN_USER="${{ vars.WORDPRESS_ADMIN_USER }}" \
            WORDPRESS_ADMIN_PASSWORD="${{ secrets.WORDPRESS_ADMIN_PASSWORD }}" \
            WORDPRESS_ADMIN_EMAIL="${{ vars.WORDPRESS_ADMIN_EMAIL }}" \
            WORDPRESS_DB_NAME="${{ vars.WORDPRESS_DB_NAME }}" \
            WORDPRESS_DB_USER="${{ vars.WORDPRESS_DB_USER }}" \
            WORDPRESS_DB_PASSWORD="${{ secrets.WORDPRESS_DB_PASSWORD }}" \
            MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            GITHUB_REPO="${{ github.repository }}" \
            GITHUB_BRANCH="${{ github.ref_name }}" \
            docker compose -f webapp/docker-compose.yml up -d
    
  configure-app:
    needs: start-containers
    uses: ./.github/workflows/app_configure.yml
    secrets:
      inherit

  validate-app:
    needs: configure-app
    uses: ./.github/workflows/app_validate.yml
    secrets:
      inherit

  notify-if-any-step-failed-or-skipped:
    needs: [prepare-environment, checkout-code, clean-up-last-build, validate-app, start-containers, configure-app]
    if: (needs.prepare-environment.result == 'failure' || needs.checkout-code.result == 'failure' || needs.clean-up-last-build.result == 'failure' || needs.start-containers.result == 'failure' || needs.configure-app.result == 'failure' || needs.validate-app.result == 'failure' || needs.prepare-environment.result == 'skipped' || needs.checkout-code.result == 'skipped' || needs.clean-up-last-build.result == 'skipped' || needs.start-containers.result == 'skipped' || needs.configure-app.result == 'skipped' || needs.validate-app.result == 'skipped')
    uses: ./.github/workflows/notification_discord.yml
    secrets:
      inherit